@summit2019API = https://delphi.pl/zlot/zlot2019/api/test

### Mailing Confirm email
GET {{summit2019API}}/cfp/


### Mailing Register email
PUT {{summit2019API}}/cfp/ HTTP/1.1
content-type: application/json

{
    "presenter": "Jan Atkinson", 
    "company": "Mr", 
    "email": "mr@bean.pl", 
    "phone": "222", 
    "bio": "Ogólnie znany jako ...", 
    "title": "Nadciąga totalny kataklizm", 
    "description": "Prowadzący w zabawny sposób przedstawi jak skutecznie ...", 
    "additional": "Opowiem jak naprawiać zniszczone obrazy ..." 
}

# ------------------------------------------------------------
# Negative tests
# ------------------------------------------------------------

### Invalid email
PUT {{summit2019API}}/cfp/
content-type: application/json

{ 
    "presenter": "Jan", 
    "company": "M", 
    "email": "mr", 
    "phone": "2", 
    "bio": "Ogólnie", 
    "title": "Nadciąga", 
    "description": "Prowadzący", 
}

