### Mailing Register email
PUT {{summit2019API}}/mailing/ HTTP/1.1
content-type: application/json

{ 
    "token": "*Demo%Insert%Token*",
    "email": "krzysztof.kowalski@gmail.com", 
    "firstname": "Krzysztof", 
    "lastname": "Kowalski", 
    "company": "" 
}

### Mailing Unregister email
DELETE {{summit2019API}}/mailing/ HTTP/1.1
content-type: application/json

{  
    "token": "*Demo%UnReg%Token*", 
    "email": "bogdan.polak@wp.pl" 
}

### Mailing Confirm email
GET {{summit2019API}}/mailing/confirmation/hashA01

# ------------------------------------------------------------
# Negative tests
#
### Invalid authorization in PUT
PUT {{summit2019API}}/mailing/
content-type: application/json

{ 
    "token": "*Demo%Bad%Token*",
    "email": "bogdan.polak@wp.pl"
}

